@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas",
  "email": "lucas5@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lucas5@gmail.com",
  "password": "123456"
}

###

# @name create_client
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Carlos Santos",
  "email": "carlossantos@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "cnpjcpf":"546.345.343-02",
  "address":"Avenida 7 de Setembro",
  "numberAddress":"822",
  "neighborhood":"Centro",
  "cep":"99670-000",
  "city":"Ronda Alta",
  "uf":"RS",
  "phone":"5499727330"
}

# @name update_client
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "id": "031e2eac-bf0c-4a5e-be73-7f274a26ad3b",
  "name": "Carlos Santos",
  "email": "carlossantos@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "cnpjcpf":"546.345.343-02",
  "address":"Avenida 7 de Setembro",
  "numberAddress":"822",
  "neighborhood":"Centro",
  "cep":"99670-000",
  "city":"Ronda Alta",
  "uf":"RS",
  "phone":"5499727330"
}

###

# @name fetch_client_by_name
GET {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Carlos"
}

