@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas",
  "email": "lucas5@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lucas5@gmail.com",
  "password": "123456"
}

###

# @name create_client
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Lucas Silva",
  "email": "lucas5@gmail.com",
  "password": "123456",
  "confirmPassword": "123456",
  "cnpjcpf":"041.726.830-02",
  "address":"Avenida 7 de Setembro",
  "numberAddress":"822",
  "neighborhood":"Centro",
  "cep":"99670-000",
  "city":"Ronda Alta",
  "uf":"RS",
  "phone":"5499727330"
}