version: '3.8'

services:
  postgres:
    container_name: backend
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gymsyncuser
      POSTGRES_PASSWORD: 12050803
      POSTGRES_DB: gymsync
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres